version: "2"
run:
  issues-exit-code: 1
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*os.File).Close
        - (io.Closer).Close
        - (*net/http.Response).Body.Close
        - (*database/sql.DB).Close
        - (*database/sql.Conn).Close
        - (github.com/pterm/pterm.TablePrinter).Render
        - (*golang.org/x/sys/windows/registry.Key).Close
        - (io.ReadCloser).Close
        - os.Remove
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
