#!/usr/bin/env bash
#
# tools/setup_hooks.sh — Install git hooks to prevent CI/CD failures
#

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="${REPO_ROOT}/.git/hooks"

if [ ! -d "$HOOKS_DIR" ]; then
    echo "Error: .git/hooks directory not found at $HOOKS_DIR"
    exit 1
fi

PRE_PUSH_HOOK="${HOOKS_DIR}/pre-push"

cat << 'EOF' > "$PRE_PUSH_HOOK"
#!/usr/bin/env bash
#
# Git pre-push hook generated by tools/setup_hooks.sh
# Ensures all local CI/CD gates pass before pushing to remote.
#

set -euo pipefail

echo "==> Running pre-push CI/CD quality gate..."
REPO_ROOT="$(git rev-parse --show-toplevel)"

# Unset git hook environment variables so sub-tests don't bleed into git repo
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_PREFIX

if ! "${REPO_ROOT}/tools/pre_push.sh" --fast; then
    echo ""
    echo "::error::git push ABORTED: pre-push verification failed."
    echo "Fix violations locally or run './tools/pre_push.sh' for full diagnostics."
    exit 1
fi

echo "==> Pre-push verification clean. Proceeding with push."
exit 0
EOF

chmod +x "$PRE_PUSH_HOOK"
echo "✓ Git pre-push hook successfully installed at ${PRE_PUSH_HOOK}"
